// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvBc3cpGs_8RXMv3Z-POG0vDpmNAwnIkI',
    appId: '1:833975987471:web:132f4ec63e800ca02b627a',
    messagingSenderId: '833975987471',
    projectId: 'trippo-42089',
    authDomain: 'trippo-42089.firebaseapp.com',
    storageBucket: 'trippo-42089.firebasestorage.app',
    measurementId: 'G-NQ1CCXPRVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5iCh00xpYX-5Q07ITRRyRz3UYoMqE2ns',
    appId: '1:833975987471:android:b89f0b689557e9e22b627a',
    messagingSenderId: '833975987471',
    projectId: 'trippo-42089',
    storageBucket: 'trippo-42089.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoe5IvSDlodUNIlQoLzxFDphABHzK7jxc',
    appId: '1:833975987471:ios:80a9f59e5c1b6fea2b627a',
    messagingSenderId: '833975987471',
    projectId: 'trippo-42089',
    storageBucket: 'trippo-42089.firebasestorage.app',
    iosBundleId: 'dev.hyderali.btripsuser',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoe5IvSDlodUNIlQoLzxFDphABHzK7jxc',
    appId: '1:833975987471:ios:80a9f59e5c1b6fea2b627a',
    messagingSenderId: '833975987471',
    projectId: 'trippo-42089',
    storageBucket: 'trippo-42089.firebasestorage.app',
    iosBundleId: 'dev.hyderali.btripsuser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvBc3cpGs_8RXMv3Z-POG0vDpmNAwnIkI',
    appId: '1:833975987471:web:0e207931c63e24472b627a',
    messagingSenderId: '833975987471',
    projectId: 'trippo-42089',
    authDomain: 'trippo-42089.firebaseapp.com',
    storageBucket: 'trippo-42089.firebasestorage.app',
    measurementId: 'G-MRRNVM9B49',
  );

}